apiVersion: v1
kind: Service
metadata:
  name: click2cloud-service
  labels:
    app: click2cloud-devops-project
spec:
  selector:
    app: click2cloud-devops-project
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31200
